language: python
python:
  - "2.7"

services:
  - postgresql
  - memcached

addons:
  postgresql: "9.4"

sudo: true

install:
  - sudo apt-get install -y pgxnclient build-essential python-dev postgresql-server-dev-9.4
  - sudo pgxn install multicorn
  - sudo python setup.py install

script:
  - psql -h localhost -U postgres -w --set ON_ERROR_STOP=on -f test/queries.sql
